M48
; DRILL file {KiCad 8.0.0-8.0.0-1~ubuntu20.04.1} date 2024-04-01T04:19:57+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-01T04:19:57+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0-8.0.0-1~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0430
%
G90
G05
T1
X3.8415Y-4.8561
X3.8415Y-5.6164
M30
