name: Lint

on: 
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

# Only one lint job runs per branch. New commits cancel old lint jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@v4
      
      - name: Ensure clang-format Installed
        run: |
          if ! command -v clang-format &> /dev/null; then
            apt-get update
            apt-get install -y clang-format
          fi
          echo "clang-format version = $(clang-format --version)"

      - name: Run Linter
        run: | 
          ./lint.sh ${{ github.workspace }}
